name: Deploy Notes Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H 5.78.134.79 > ~/.ssh/known_hosts

      - name: Build JAR
        run: |
          ./gradlew bootJar

      - name: Deploy JAR to Server
        run: |
          JAR_NAME="demo-0.0.1-SNAPSHOT.jar"
          LOCAL_JAR_PATH="build/libs/$JAR_NAME"
          REMOTE_SERVER="admin@5.78.134.79"
          REMOTE_JAR_DIR="/opt/wordoftheday"

          rsync -avz -e "ssh" $LOCAL_JAR_PATH $REMOTE_SERVER:$REMOTE_JAR_DIR/$JAR_NAME

          ssh $REMOTE_SERVER << EOF
            mv $REMOTE_JAR_DIR/$JAR_NAME $REMOTE_JAR_DIR/wordoftheday.jar
            sudo systemctl restart wordoftheday.service
          EOF