name: Deploy to Server

on:
  push:
    branches:
      - main  # 메인 브랜치 푸시 시 배포

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 5.78.134.79 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build JAR
        run: |
          ./gradlew clean build -x test

      - name: Deploy to server
        run: |
          JAR_NAME="demo-0.0.1-SNAPSHOT.jar"
          LOCAL_JAR_PATH="build/libs/$JAR_NAME"
          REMOTE_SERVER="admin@5.78.134.79"
          REMOTE_JAR_DIR="/opt/wordoftheday"

          # JAR 업로드
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" $LOCAL_JAR_PATH $REMOTE_SERVER:$REMOTE_JAR_DIR/$JAR_NAME

          # JAR 교체 및 서비스 재시작
          ssh -i ~/.ssh/id_rsa $REMOTE_SERVER << EOF
            mv $REMOTE_JAR_DIR/$JAR_NAME $REMOTE_JAR_DIR/wordoftheday.jar
            sudo systemctl restart wordoftheday.service
          EOF